In [26]:
import matplotlib.pyplot as plt
import pandas as pd
import os
import pydicom as dicom
from glob import glob

In [17]:
root_dir= "/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/"

df_train_main  = pd.read_csv(root_dir + 'train.csv')
df_train_label = pd.read_csv(root_dir + 'train_label_coordinates.csv')
df_train_desc  = pd.read_csv(root_dir + 'train_series_descriptions.csv')
df_test_desc   = pd.read_csv(root_dir + 'test_series_descriptions.csv')
df_sub         = pd.read_csv(root_dir + 'sample_submission.csv')

In [18]:
df_train_main

,study_id,spinal_canal_stenosis_l1_l2,spinal_canal_stenosis_l2_l3,spinal_canal_stenosis_l3_l4,spinal_canal_stenosis_l4_l5,spinal_canal_stenosis_l5_s1,left_neural_foraminal_narrowing_l1_l2,left_neural_foraminal_narrowing_l2_l3,left_neural_foraminal_narrowing_l3_l4,left_neural_foraminal_narrowing_l4_l5,...,left_subarticular_stenosis_l1_l2,left_subarticular_stenosis_l2_l3,left_subarticular_stenosis_l3_l4,left_subarticular_stenosis_l4_l5,left_subarticular_stenosis_l5_s1,right_subarticular_stenosis_l1_l2,right_subarticular_stenosis_l2_l3,right_subarticular_stenosis_l3_l4,right_subarticular_stenosis_l4_l5,right_subarticular_stenosis_l5_s1
0,4003253,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Moderate,...,Normal/Mild,Normal/Mild,Normal/Mild,Moderate,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild
1,4646740,Normal/Mild,Normal/Mild,Moderate,Severe,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Moderate,...,Normal/Mild,Normal/Mild,Normal/Mild,Severe,Normal/Mild,Normal/Mild,Moderate,Moderate,Moderate,Normal/Mild
2,7143189,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,...,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild
3,8785691,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Moderate,...,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild
4,10728036,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,...,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Moderate,Normal/Mild
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1970,4282019580,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Moderate,...,Normal/Mild,Normal/Mild,Normal/Mild,Moderate,Normal/Mild,Normal/Mild,Normal/Mild,Moderate,Moderate,Moderate
1971,4283570761,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,...,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild
1972,4284048608,Normal/Mild,Normal/Mild,Normal/Mild,Severe,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,...,Normal/Mild,Normal/Mild,Normal/Mild,Severe,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Severe,Normal/Mild
1973,4287160193,Normal/Mild,Moderate,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Moderate,...,Normal/Mild,Severe,Moderate,Moderate,Normal/Mild,Normal/Mild,Normal/Mild,Moderate,Moderate,Normal/Mild
1974,4290709089,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,...,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild

In [35]:
df_train_label.condition.unique()

array(['Spinal Canal Stenosis', 'Right Neural Foraminal Narrowing',
       'Left Neural Foraminal Narrowing', 'Left Subarticular Stenosis',
       'Right Subarticular Stenosis'], dtype=object)

In [34]:
def id2root_dir(root_dir,study_id):
    path = os.path.join(root_dir,"train_images",str(study_id))
    path_s = glob(path + "/**")
    return path_s

for i,row in df_train_main.iterrows():

    path_s = id2root_dir(
        root_dir,
        row["study_id"],
        # row["series_id"],
        # row["instance_number"]
        )
    print(path_s)

    # ds = dicom.dcmread(path)

    # fig, ax = plt.subplots(figsize=(16, 8))
    # from matplotlib.colors import LogNorm 

    # ax.imshow(ds.pixel_array, cmap ='CMRmap')     # Display the image
    
    if i > 30:
        break

['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/4003253/1054713880', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/4003253/2448190387', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/4003253/702807833']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/4646740/3201256954', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/4646740/3486248476', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/4646740/3666319702']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/7143189/132939515', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/7143189/1951927562', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/7143189/3219733239']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/8785691/1570286759', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/8785691/2406919186', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/8785691/481125819']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/10728036/142859125', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/10728036/2073726394', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/10728036/2399638375', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/10728036/3491739931']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/11340341/1224932122', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/11340341/2231042680', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/11340341/3543553307']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/11943292/1212326388', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/11943292/1638921810', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/11943292/3800798510', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/11943292/403244853']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/13317052/1539051863', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/13317052/2500166693', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/13317052/2677627096']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/22191399/3687121182', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/22191399/3753885158', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/22191399/434280813']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/26342422/1679014482', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/26342422/226564374', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/26342422/2528347280', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/26342422/307069509']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/29931867/1152175603', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/29931867/1676821058', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/29931867/2261718442', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/29931867/231278500']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/33736057/1379151387', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/33736057/1847558962', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/33736057/758801267']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/38281420/1178941473', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/38281420/2565838687', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/38281420/880361156']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/40745534/1395478236', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/40745534/2948359731', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/40745534/3918681171']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/41477684/2595734107', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/41477684/3009399271', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/41477684/3749739759']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/44060036/1034241723', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/44060036/2320605986', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/44060036/3055212151', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/44060036/3294158542']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/46494080/1543341132', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/46494080/1763376930', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/46494080/4061588226']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/52397721/2452297573', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/52397721/2770638094', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/52397721/3220885418']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/52695609/32135551', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/52695609/3284178089', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/52695609/3778925627', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/52695609/3993996421']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/53418228/1921001089', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/53418228/2698575616', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/53418228/345993377']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/58813022/302608236', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/58813022/3875372861', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/58813022/692718517']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/59576878/1757508642', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/59576878/1786504756', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/59576878/2414228193']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/60612428/2349970136', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/60612428/3446457669', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/60612428/661972121']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/63725508/1069611138', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/63725508/1389849895', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/63725508/1547488253', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/63725508/2144061947']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/64092030/1233796867', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/64092030/1924652166', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/64092030/3762658078']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/69086098/1872368754', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/69086098/2449982462', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/69086098/475539618']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/70878995/2807935482', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/70878995/3022642562', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/70878995/3493432031']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/71973234/1433976441', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/71973234/1858127754', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/71973234/2627968392']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/73783367/1885677897', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/73783367/2087785373', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/73783367/2639788488']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/74294498/3485741709', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/74294498/3742439825', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/74294498/507422603']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/74782131/2676982925', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/74782131/2762032004', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/74782131/3401861580']
['/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/75336136/1335435066', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/75336136/3843947211', '/mnt/d/data/rsna-2024-lumbar-spine-degenerative-classification/train_images/75336136/779328287']

df_train_main には、１つの検体（study_id）のそれぞれの箇所について、重症度のラベルが書いてある
df_train_labelのx,yには、それぞれの箇所の座標が具体的にどこか、が書いてあるね

In [24]:
ds.pixel_array

array([[ 5,  6,  7, ...,  0,  0,  0],
       [ 5,  8, 12, ...,  0,  0,  0],
       [ 5,  8, 15, ...,  0,  0,  0],
       ...,
       [ 3,  6,  7, ...,  0,  0,  0],
       [ 3,  5,  7, ...,  0,  0,  0],
       [ 3,  2,  2, ...,  0,  0,  0]], dtype=uint16)

In [21]:
df_train_desc

        study_id   series_id series_description
0        4003253   702807833   Sagittal T2/STIR
1        4003253  1054713880        Sagittal T1
2        4003253  2448190387           Axial T2
3        4646740  3201256954           Axial T2
4        4646740  3486248476        Sagittal T1
...          ...         ...                ...
6289  4287160193  1507070277   Sagittal T2/STIR
6290  4287160193  1820446240           Axial T2
6291  4290709089  3274612423   Sagittal T2/STIR
6292  4290709089  3390218084           Axial T2
6293  4290709089  4237840455        Sagittal T1

[6294 rows x 3 columns]